// FILE: src/app/api/invoices/route.ts
// GET all invoices, POST create new invoice

import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase/server';

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const status = searchParams.get('status');
  const search = searchParams.get('search');
  const patientId = searchParams.get('patient_id');

  if (!supabaseAdmin) {
    return NextResponse.json(
      { error: 'Supabase not configured' },
      { status: 500 }
    );
  }

  try {
    let query = supabaseAdmin
      .from('invoices')
      .select(`*, insurance_companies(company_code,company_name,company_name_ar)`)
      .eq('is_deleted', false)
      .order('invoice_date', { ascending: false });

    if (status && status !== 'ALL') query = query.eq('status', status);
    if (patientId) query = query.eq('patient_id', patientId);
    if (search) query = query.or(`invoice_number.ilike.%${search}%,patient_name.ilike.%${search}%`);

    const { data, error } = await query;

    if (error) {
      console.error('Supabase invoices error:', error?.message);
      return NextResponse.json(
        { error: 'Failed to fetch invoices', details: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json(data || []);

  } catch (err: any) {
    console.error('GET invoices exception:', err?.message);
    return NextResponse.json(
      { error: 'Failed to fetch invoices', details: err.message },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const supabase = supabaseAdmin;
    const body = await request.json();

    console.log('📝 Creating invoice:', body.invoice_number);
    console.log('📋 Request body items:', body.items);
    console.log('📋 Items count:', body.items?.length || 0);
    console.log('📋 Full request body:', JSON.stringify(body, null, 2));

    // Get organization ID
    const { data: orgs } = await supabase
      .from('organizations')
      .select('id')
      .limit(1);
    const orgId = orgs?.[0]?.id || '00000000-0000-0000-0000-000000000000';

    // Prepare invoice data
    const invoiceData: any = {
      organization_id: orgId,
      invoice_number: body.invoice_number || null, // Will be auto-generated by database trigger if null
      invoice_date: body.invoice_date || new Date().toISOString().split('T')[0],
      patient_id: body.patient_id || null,
      patient_name: body.patient_name || null,
      patient_name_ar: body.patient_name_ar || null,
      subtotal: body.subtotal || 0,
      discount_percentage: body.discount_percentage || 0,
      discount_amount: body.discount_amount || 0,
      tax_percentage: body.tax_percentage || 0,
      tax_amount: body.tax_amount || 0,
      total_amount: body.total_amount || 0,
      insurance_company_id: body.insurance_company_id || null,
      insurance_coverage_amount: body.insurance_coverage_amount || 0,
      insurance_coverage_percentage: body.insurance_coverage_percentage || 0,
      patient_responsibility: body.patient_responsibility || 0,
      amount_paid: body.amount_paid || 0,
      balance_due: body.balance_due || 0,
      status: body.status || 'PENDING',
      payment_method: body.payment_method || null,
      payment_date: body.payment_date || null,
      payment_reference: body.payment_reference || null,
      responsible_entity_type: body.responsible_entity_type || null,
      responsible_entity_id: body.responsible_entity_id || null,
      notes: body.notes || null,
    };

    const { data, error } = await supabase
      .from('invoices')
      .insert(invoiceData)
      .select()
      .single();

    if (error) {
      console.error('Error creating invoice:', error);
      return NextResponse.json(
        { error: error.message },
        { status: 500 }
      );
    }

    // Insert invoice items if provided
    if (body.items && Array.isArray(body.items) && body.items.length > 0) {
      console.log('✅ Items array found, preparing to insert:', body.items.length, 'items');
      
      const items = body.items.map((item: any) => ({
        invoice_id: data.id,
        item_type: item.item_type,
        item_code: item.item_code || null,
        item_name: item.item_name,
        item_name_ar: item.item_name_ar || null,
        description: item.description || null,
        quantity: item.quantity || 1,
        unit_price: item.unit_price,
        discount_percentage: item.discount_percentage || 0,
        discount_amount: item.discount_amount || 0,
        subtotal: item.subtotal,
        insurance_covered: item.insurance_covered || false,
        insurance_coverage_percentage: item.insurance_coverage_percentage || 0,
        insurance_amount: item.insurance_amount || 0,
        patient_amount: item.patient_amount || 0,
        provider_id: item.provider_id || null,
        provider_name: item.provider_name || null,
        service_fee: item.service_fee || 0,
              }));

      console.log('📦 Prepared items for insert:', JSON.stringify(items, null, 2));

      const { data: insertedItems, error: itemsError } = await supabase
        .from('invoice_items')
        .insert(items)
        .select();

      if (itemsError) {
        console.error('❌ Error creating invoice items:', itemsError);
        console.error('❌ Items that failed:', JSON.stringify(items, null, 2));
        // Return error so we know items failed
        return NextResponse.json(
          { 
            error: 'Invoice created but items failed to save',
            invoiceId: data.id,
            itemsError: itemsError.message,
            details: itemsError
          },
          { status: 500 }
        );
      } else {
        console.log('✅ Invoice items created successfully:', insertedItems?.length || 0, 'items');
      }
    } else {
      console.warn('⚠️ No items provided in request body');
      console.warn('⚠️ body.items:', body.items);
      console.warn('⚠️ Is array?', Array.isArray(body.items));
      console.warn('⚠️ Length:', body.items?.length);
    }

    console.log('✅ Invoice created:', data.id);
    return NextResponse.json(data, { status: 201 });

  } catch (error: any) {
    console.error('POST invoice error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to create invoice' },
      { status: 500 }
    );
  }
}
