-- Phase 04 (group A): row-level security on every table carrying a tenant
-- column directly. 148 tables.
--
-- The tenant travels on the connection: each request opens a transaction and
-- issues SET LOCAL app.workspace_id, taken from the verified session and never
-- from the URL. NULLIF is essential — once a SET LOCAL ends the setting reads
-- back as an empty string, and ''::uuid raises an error instead of matching
-- nothing. NULL simply compares false, so an unset tenant sees zero rows.
--
-- USING governs reads, WITH CHECK governs writes, and WITH CHECK never allows
-- NULL: a row may be readable as global but must still be written with an
-- owner.
--
-- patients and notifications also accept NULL as "global, visible to every
-- facility" — that is a deliberate state with an admin route behind it
-- (/api/admin/patients/make-global), and 160 of 169 patients rely on it.
-- Everywhere else a NULL would be an orphan and stays invisible.
--
-- FORCE is included so table ownership cannot bypass the policy either.
--
-- Applied to production on 2026-08-22. Invisible to the running application
-- until its connection string moves to app_user: neondb_owner has BYPASSRLS.

ALTER TABLE "ap_invoices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ap_invoices" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ap_invoices";
CREATE POLICY tenant_isolation ON "ap_invoices" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "application_stage_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "application_stage_history" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "application_stage_history";
CREATE POLICY tenant_isolation ON "application_stage_history" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "appointments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "appointments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "appointments";
CREATE POLICY tenant_isolation ON "appointments" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "assessment_tests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "assessment_tests" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "assessment_tests";
CREATE POLICY tenant_isolation ON "assessment_tests" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "attendance_exceptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "attendance_exceptions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "attendance_exceptions";
CREATE POLICY tenant_isolation ON "attendance_exceptions" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "attendance_transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "attendance_transactions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "attendance_transactions";
CREATE POLICY tenant_isolation ON "attendance_transactions" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "background_checks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "background_checks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "background_checks";
CREATE POLICY tenant_isolation ON "background_checks" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "bank_details" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bank_details" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "bank_details";
CREATE POLICY tenant_isolation ON "bank_details" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "bank_transfers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bank_transfers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "bank_transfers";
CREATE POLICY tenant_isolation ON "bank_transfers" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "budget_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "budget_categories" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "budget_categories";
CREATE POLICY tenant_isolation ON "budget_categories" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "budget_periods" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "budget_periods" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "budget_periods";
CREATE POLICY tenant_isolation ON "budget_periods" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "candidate_assessments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "candidate_assessments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "candidate_assessments";
CREATE POLICY tenant_isolation ON "candidate_assessments" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "candidate_communications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "candidate_communications" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "candidate_communications";
CREATE POLICY tenant_isolation ON "candidate_communications" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "candidate_documents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "candidate_documents" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "candidate_documents";
CREATE POLICY tenant_isolation ON "candidate_documents" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "candidate_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "candidate_notes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "candidate_notes";
CREATE POLICY tenant_isolation ON "candidate_notes" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "daily_attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "daily_attendance" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "daily_attendance";
CREATE POLICY tenant_isolation ON "daily_attendance" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "daily_schedule_details" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "daily_schedule_details" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "daily_schedule_details";
CREATE POLICY tenant_isolation ON "daily_schedule_details" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "departments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "departments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "departments";
CREATE POLICY tenant_isolation ON "departments" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "drugs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "drugs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "drugs";
CREATE POLICY tenant_isolation ON "drugs" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "emergency_doctor_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "emergency_doctor_assignments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "emergency_doctor_assignments";
CREATE POLICY tenant_isolation ON "emergency_doctor_assignments" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "emergency_doctor_availability" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "emergency_doctor_availability" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "emergency_doctor_availability";
CREATE POLICY tenant_isolation ON "emergency_doctor_availability" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "employee_advances" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "employee_advances" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "employee_advances";
CREATE POLICY tenant_isolation ON "employee_advances" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "employee_compensation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "employee_compensation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "employee_compensation";
CREATE POLICY tenant_isolation ON "employee_compensation" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "employee_loans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "employee_loans" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "employee_loans";
CREATE POLICY tenant_isolation ON "employee_loans" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "employee_profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "employee_profile" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "employee_profile";
CREATE POLICY tenant_isolation ON "employee_profile" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "employee_recognitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "employee_recognitions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "employee_recognitions";
CREATE POLICY tenant_isolation ON "employee_recognitions" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "employee_schedules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "employee_schedules" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "employee_schedules";
CREATE POLICY tenant_isolation ON "employee_schedules" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "employees" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "employees" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "employees";
CREATE POLICY tenant_isolation ON "employees" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "employment_details" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "employment_details" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "employment_details";
CREATE POLICY tenant_isolation ON "employment_details" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "evaluation_criteria" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "evaluation_criteria" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "evaluation_criteria";
CREATE POLICY tenant_isolation ON "evaluation_criteria" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_accounts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_accounts";
CREATE POLICY tenant_isolation ON "fin_accounts" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_ap_invoices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_ap_invoices" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_ap_invoices";
CREATE POLICY tenant_isolation ON "fin_ap_invoices" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_ap_payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_ap_payments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_ap_payments";
CREATE POLICY tenant_isolation ON "fin_ap_payments" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_ar_transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_ar_transactions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_ar_transactions";
CREATE POLICY tenant_isolation ON "fin_ar_transactions" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_audit_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_audit_log" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_audit_log";
CREATE POLICY tenant_isolation ON "fin_audit_log" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_bank_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_bank_accounts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_bank_accounts";
CREATE POLICY tenant_isolation ON "fin_bank_accounts" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_journal_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_journal_entries" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_journal_entries";
CREATE POLICY tenant_isolation ON "fin_journal_entries" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_journal_lines" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_journal_lines" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_journal_lines";
CREATE POLICY tenant_isolation ON "fin_journal_lines" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_periods" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_periods" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_periods";
CREATE POLICY tenant_isolation ON "fin_periods" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_tax_codes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_tax_codes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_tax_codes";
CREATE POLICY tenant_isolation ON "fin_tax_codes" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "fin_vendors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fin_vendors" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fin_vendors";
CREATE POLICY tenant_isolation ON "fin_vendors" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "goods_receipt_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "goods_receipt_notes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "goods_receipt_notes";
CREATE POLICY tenant_isolation ON "goods_receipt_notes" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_batches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_batches" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_batches";
CREATE POLICY tenant_isolation ON "hospital_batches" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_claim_damage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_claim_damage" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_claim_damage";
CREATE POLICY tenant_isolation ON "hospital_claim_damage" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_departments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_departments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_departments";
CREATE POLICY tenant_isolation ON "hospital_departments" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_dispenses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_dispenses" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_dispenses";
CREATE POLICY tenant_isolation ON "hospital_dispenses" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_goods_receipt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_goods_receipt" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_goods_receipt";
CREATE POLICY tenant_isolation ON "hospital_goods_receipt" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_goods_receipt_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_goods_receipt_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_goods_receipt_items";
CREATE POLICY tenant_isolation ON "hospital_goods_receipt_items" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_history" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_history";
CREATE POLICY tenant_isolation ON "hospital_history" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_items";
CREATE POLICY tenant_isolation ON "hospital_items" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_manufacturers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_manufacturers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_manufacturers";
CREATE POLICY tenant_isolation ON "hospital_manufacturers" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_order_items_new" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_order_items_new" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_order_items_new";
CREATE POLICY tenant_isolation ON "hospital_order_items_new" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_orders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_orders";
CREATE POLICY tenant_isolation ON "hospital_orders" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_purchase_note_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_purchase_note_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_purchase_note_items";
CREATE POLICY tenant_isolation ON "hospital_purchase_note_items" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_purchase_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_purchase_notes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_purchase_notes";
CREATE POLICY tenant_isolation ON "hospital_purchase_notes" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_stock" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_stock" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_stock";
CREATE POLICY tenant_isolation ON "hospital_stock" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_storage_locations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_storage_locations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_storage_locations";
CREATE POLICY tenant_isolation ON "hospital_storage_locations" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_transfer_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_transfer_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_transfer_items";
CREATE POLICY tenant_isolation ON "hospital_transfer_items" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_transfers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_transfers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_transfers";
CREATE POLICY tenant_isolation ON "hospital_transfers" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "hospital_wastage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hospital_wastage" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "hospital_wastage";
CREATE POLICY tenant_isolation ON "hospital_wastage" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "insurance_claims" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "insurance_claims" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "insurance_claims";
CREATE POLICY tenant_isolation ON "insurance_claims" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "insurance_companies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "insurance_companies" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "insurance_companies";
CREATE POLICY tenant_isolation ON "insurance_companies" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "insurance_company_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "insurance_company_categories" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "insurance_company_categories";
CREATE POLICY tenant_isolation ON "insurance_company_categories" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "insurance_company_plan_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "insurance_company_plan_types" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "insurance_company_plan_types";
CREATE POLICY tenant_isolation ON "insurance_company_plan_types" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "insurance_pre_approvals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "insurance_pre_approvals" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "insurance_pre_approvals";
CREATE POLICY tenant_isolation ON "insurance_pre_approvals" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "interview_evaluations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "interview_evaluations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "interview_evaluations";
CREATE POLICY tenant_isolation ON "interview_evaluations" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "interview_panel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "interview_panel" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "interview_panel";
CREATE POLICY tenant_isolation ON "interview_panel" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "interviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "interviews" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "interviews";
CREATE POLICY tenant_isolation ON "interviews" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "invoice_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoice_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "invoice_items";
CREATE POLICY tenant_isolation ON "invoice_items" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "invoice_returns" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoice_returns" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "invoice_returns";
CREATE POLICY tenant_isolation ON "invoice_returns" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "invoice_shares" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoice_shares" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "invoice_shares";
CREATE POLICY tenant_isolation ON "invoice_shares" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "invoices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoices" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "invoices";
CREATE POLICY tenant_isolation ON "invoices" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "items";
CREATE POLICY tenant_isolation ON "items" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "job_applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_applications" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "job_applications";
CREATE POLICY tenant_isolation ON "job_applications" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "job_candidates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_candidates" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "job_candidates";
CREATE POLICY tenant_isolation ON "job_candidates" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "job_offers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_offers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "job_offers";
CREATE POLICY tenant_isolation ON "job_offers" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "job_requisitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_requisitions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "job_requisitions";
CREATE POLICY tenant_isolation ON "job_requisitions" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "job_vacancies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_vacancies" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "job_vacancies";
CREATE POLICY tenant_isolation ON "job_vacancies" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "lab_claims" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lab_claims" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "lab_claims";
CREATE POLICY tenant_isolation ON "lab_claims" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "lab_consumption_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lab_consumption_log" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "lab_consumption_log";
CREATE POLICY tenant_isolation ON "lab_consumption_log" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "lab_goods_receipt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lab_goods_receipt" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "lab_goods_receipt";
CREATE POLICY tenant_isolation ON "lab_goods_receipt" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "lab_payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lab_payments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "lab_payments";
CREATE POLICY tenant_isolation ON "lab_payments" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "lab_purchase_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lab_purchase_orders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "lab_purchase_orders";
CREATE POLICY tenant_isolation ON "lab_purchase_orders" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "lab_receipt_reprints" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lab_receipt_reprints" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "lab_receipt_reprints";
CREATE POLICY tenant_isolation ON "lab_receipt_reprints" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "lab_shifts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lab_shifts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "lab_shifts";
CREATE POLICY tenant_isolation ON "lab_shifts" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "lab_vendor_returns" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lab_vendor_returns" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "lab_vendor_returns";
CREATE POLICY tenant_isolation ON "lab_vendor_returns" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "leave_balance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "leave_balance" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "leave_balance";
CREATE POLICY tenant_isolation ON "leave_balance" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "leave_request_approvals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "leave_request_approvals" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "leave_request_approvals";
CREATE POLICY tenant_isolation ON "leave_request_approvals" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "leave_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "leave_requests" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "leave_requests";
CREATE POLICY tenant_isolation ON "leave_requests" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "leave_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "leave_types" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "leave_types";
CREATE POLICY tenant_isolation ON "leave_types" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "manufacturers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "manufacturers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "manufacturers";
CREATE POLICY tenant_isolation ON "manufacturers" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "national_id" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "national_id" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "national_id";
CREATE POLICY tenant_isolation ON "national_id" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "notifications";
CREATE POLICY tenant_isolation ON "notifications" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid OR workspaceid IS NULL) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "offer_negotiation_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "offer_negotiation_history" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "offer_negotiation_history";
CREATE POLICY tenant_isolation ON "offer_negotiation_history" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "official_holidays" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "official_holidays" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "official_holidays";
CREATE POLICY tenant_isolation ON "official_holidays" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "operation_prices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "operation_prices" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "operation_prices";
CREATE POLICY tenant_isolation ON "operation_prices" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "operations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "operations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "operations";
CREATE POLICY tenant_isolation ON "operations" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "patient_credit_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "patient_credit_accounts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "patient_credit_accounts";
CREATE POLICY tenant_isolation ON "patient_credit_accounts" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "patient_reminders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "patient_reminders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "patient_reminders";
CREATE POLICY tenant_isolation ON "patient_reminders" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "patients" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "patients" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "patients";
CREATE POLICY tenant_isolation ON "patients" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid OR workspaceid IS NULL) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "payroll_approvals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payroll_approvals" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "payroll_approvals";
CREATE POLICY tenant_isolation ON "payroll_approvals" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "payroll_periods" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payroll_periods" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "payroll_periods";
CREATE POLICY tenant_isolation ON "payroll_periods" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "payroll_transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payroll_transactions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "payroll_transactions";
CREATE POLICY tenant_isolation ON "payroll_transactions" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "performance_reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "performance_reviews" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "performance_reviews";
CREATE POLICY tenant_isolation ON "performance_reviews" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "pharmacies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pharmacies" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pharmacies";
CREATE POLICY tenant_isolation ON "pharmacies" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "pharmacy_goods_receipt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pharmacy_goods_receipt" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pharmacy_goods_receipt";
CREATE POLICY tenant_isolation ON "pharmacy_goods_receipt" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "pharmacy_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pharmacy_orders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pharmacy_orders";
CREATE POLICY tenant_isolation ON "pharmacy_orders" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "pharmacy_purchase_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pharmacy_purchase_orders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pharmacy_purchase_orders";
CREATE POLICY tenant_isolation ON "pharmacy_purchase_orders" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "pharmacy_stock_locations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pharmacy_stock_locations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pharmacy_stock_locations";
CREATE POLICY tenant_isolation ON "pharmacy_stock_locations" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "pos_receipt_reprints" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pos_receipt_reprints" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pos_receipt_reprints";
CREATE POLICY tenant_isolation ON "pos_receipt_reprints" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "pos_return_reasons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pos_return_reasons" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pos_return_reasons";
CREATE POLICY tenant_isolation ON "pos_return_reasons" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "pos_returns" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pos_returns" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pos_returns";
CREATE POLICY tenant_isolation ON "pos_returns" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "pos_sales" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pos_sales" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pos_sales";
CREATE POLICY tenant_isolation ON "pos_sales" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "pos_shifts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pos_shifts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pos_shifts";
CREATE POLICY tenant_isolation ON "pos_shifts" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "profit_distributions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "profit_distributions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "profit_distributions";
CREATE POLICY tenant_isolation ON "profit_distributions" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "promotions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "promotions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "promotions";
CREATE POLICY tenant_isolation ON "promotions" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "purchase_order_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "purchase_order_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "purchase_order_items";
CREATE POLICY tenant_isolation ON "purchase_order_items" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "purchase_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "purchase_orders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "purchase_orders";
CREATE POLICY tenant_isolation ON "purchase_orders" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "recruitment_metrics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "recruitment_metrics" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "recruitment_metrics";
CREATE POLICY tenant_isolation ON "recruitment_metrics" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "recruitment_source_metrics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "recruitment_source_metrics" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "recruitment_source_metrics";
CREATE POLICY tenant_isolation ON "recruitment_source_metrics" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "recruitment_stages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "recruitment_stages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "recruitment_stages";
CREATE POLICY tenant_isolation ON "recruitment_stages" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "reference_checks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reference_checks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "reference_checks";
CREATE POLICY tenant_isolation ON "reference_checks" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "requisition_approval_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "requisition_approval_history" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "requisition_approval_history";
CREATE POLICY tenant_isolation ON "requisition_approval_history" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "salary_grades" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "salary_grades" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "salary_grades";
CREATE POLICY tenant_isolation ON "salary_grades" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "service_payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "service_payments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "service_payments";
CREATE POLICY tenant_isolation ON "service_payments" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "service_stakeholders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "service_stakeholders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "service_stakeholders";
CREATE POLICY tenant_isolation ON "service_stakeholders" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "services" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "services" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "services";
CREATE POLICY tenant_isolation ON "services" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "settlement_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "settlement_rules" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "settlement_rules";
CREATE POLICY tenant_isolation ON "settlement_rules" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "shareholder_distributions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "shareholder_distributions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "shareholder_distributions";
CREATE POLICY tenant_isolation ON "shareholder_distributions" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "shareholders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "shareholders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "shareholders";
CREATE POLICY tenant_isolation ON "shareholders" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "shifts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "shifts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "shifts";
CREATE POLICY tenant_isolation ON "shifts" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "specialties" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "specialties" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "specialties";
CREATE POLICY tenant_isolation ON "specialties" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "staff" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "staff" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "staff";
CREATE POLICY tenant_isolation ON "staff" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "stakeholders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stakeholders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "stakeholders";
CREATE POLICY tenant_isolation ON "stakeholders" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "stock_adjustments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_adjustments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "stock_adjustments";
CREATE POLICY tenant_isolation ON "stock_adjustments" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "stock_transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stock_transactions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "stock_transactions";
CREATE POLICY tenant_isolation ON "stock_transactions" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "stores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stores" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "stores";
CREATE POLICY tenant_isolation ON "stores" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "test_packages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "test_packages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "test_packages";
CREATE POLICY tenant_isolation ON "test_packages" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "test_reference_audit_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "test_reference_audit_log" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "test_reference_audit_log";
CREATE POLICY tenant_isolation ON "test_reference_audit_log" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "test_reference_ranges" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "test_reference_ranges" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "test_reference_ranges";
CREATE POLICY tenant_isolation ON "test_reference_ranges" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "todos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "todos" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "todos";
CREATE POLICY tenant_isolation ON "todos" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "unit_conversions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "unit_conversions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "unit_conversions";
CREATE POLICY tenant_isolation ON "unit_conversions" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "vendors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "vendors" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "vendors";
CREATE POLICY tenant_isolation ON "vendors" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "warehouse_sections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "warehouse_sections" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "warehouse_sections";
CREATE POLICY tenant_isolation ON "warehouse_sections" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "warehouses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "warehouses" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "warehouses";
CREATE POLICY tenant_isolation ON "warehouses" USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "worklists" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "worklists" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "worklists";
CREATE POLICY tenant_isolation ON "worklists" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "workspaces" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workspaces" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "workspaces";
CREATE POLICY tenant_isolation ON "workspaces" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
ALTER TABLE "workspaceusers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workspaceusers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "workspaceusers";
CREATE POLICY tenant_isolation ON "workspaceusers" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')::uuid);

-- These 15 store the tenant as text rather than uuid, so the comparison stays
-- in text: casting the setting to uuid raises "operator does not exist:
-- text = uuid" and leaves the table with RLS on and no policy, which denies
-- everything. Worth normalising these columns to uuid later.
CREATE POLICY tenant_isolation ON "accession_samples" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "equipment" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "lab_test_catalog" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "laboratory_types" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "lims_orders" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "materials" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "qc_runs" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "result_validation_history" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "sample_storage" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "samples" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "shop_orders" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "storage_locations" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "study_protocols" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "suppliers" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
CREATE POLICY tenant_isolation ON "test_results" USING (workspaceid = NULLIF(current_setting('app.workspace_id', true), '')) WITH CHECK (workspaceid = NULLIF(current_setting('app.workspace_id', true), ''));
